spring:
  application:
    name: main-server
  sleuth:
    enabled: true
    sampler:
      probability: 0.5
  zipkin:
    base-url: http://3.38.28.154:9411/
  rabbitmq: # RabbitMQ 관련 설정
    host: 3.38.31.74
    port: 5672
    username: bts
    password: "{cipher}e23db7ec02ab706c93bee68f4f2637c81fc7681d55d6481d128e9cb3535409d2"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bts
    username: bts
    password: btsbts12
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  redis:
    host: redisstock
    port: 6379
server:
  port: 8080
eureka:
  instance:
    instance-id: main-ms-instance
    hostname: 3.38.43.67

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.38.31.74:8761/eureka/